export const TOGGLE_ZOOM_MODE = 'TOGGLE_ZOOM_MODE';
export const ZOOM_FIT = 'ZOOM_FIT';
export const ZOOM_EXPAND = 'ZOOM_EXPAND';
export const ZOOM_FREE = 'ZOOM_FREE';
export const TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE';
export const TOGGLE_UI_HIDDEN = 'TOGGLE_UI_HIDDEN';
export const HIDE_UI = 'HIDE_UI';
export const SHOW_UI = 'SHOW_UI';
export const UPDATE_SCALE = 'SET_SCALE';
export const UPDATE_FILESYSTEM = 'UPDATE_FILESYSTEM';
// files
export const UPDATE_FILELIST = 'UPDATE_FILELIST';
export const UPDATE_CURRENT_FILE = 'UPDATE_CURRENT_FILE';
export const UPDATE_FILE_PROPS = 'UPDATE_FILE_PROPS';
export const UPDATE_CURRENT_POSITION = 'UPDATE_CURRENT_POSITION';
export const UPDATE_DIR = 'UPDATE_DIR';
export const UPDATE_BASE64 = 'UPDATE_BASE64';
