export const TOGGLE_ZOOM_MODE = 'TOGGLE_ZOOM_MODE';
export const UPDATE_BG_COLOR = 'UPDATE_BG_COLOR';
export const ZOOM_FIT = 'ZOOM_FIT';
export const ZOOM_EXPAND = 'ZOOM_EXPAND';
export const ZOOM_FREE = 'ZOOM_FREE';
export const SET_ZOOM_MODE = 'SET_ZOOM_MODE';
export const TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE';
export const TOGGLE_UI_HIDDEN = 'TOGGLE_UI_HIDDEN';
export const HIDE_UI = 'HIDE_UI';
export const SHOW_UI = 'SHOW_UI';
export const UPDATE_SCALE = 'SET_SCALE';
export const UPDATE_FILESYSTEM = 'UPDATE_FILESYSTEM';
export const SET_SHUFFLE = 'SET_SHUFFLE';
export const UPDATE_IMAGE_POSITION = 'UPDATE_IMAGE_POSITION';
export const RESET_IMAGE_POSITION = 'RESET_IMAGE_POSITION';
export const UPDATE_CURRENT_BLOB = 'UPDATE_CURRENT_BLOB';

// files
export const UPDATE_FILELIST = 'UPDATE_FILELIST';
export const UPDATE_CURRENT_FILE = 'UPDATE_CURRENT_FILE';
export const UPDATE_FILE_PROPS = 'UPDATE_FILE_PROPS';
export const UPDATE_CURRENT_POSITION = 'UPDATE_CURRENT_POSITION';
export const UPDATE_DIR = 'UPDATE_DIR';
export const UPDATE_BASE64 = 'UPDATE_BASE64';
export const UPDATE_TRASH = 'UPDATE_TRASH';

// popups
export const TOGGLE_POPUP = 'TOGGLE_POPUP';
export const ADD_POPUP = 'ADD_POPUP';
export const REMOVE_POPUP = 'REMOVE_POPUP';
